//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorParaVentaDeLoteria.UI.ServicioDeSorteo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioDeSorteo.IServicioDeSorteo")]
    public interface IServicioDeSorteo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDeSorteo/Listar", ReplyAction="http://tempuri.org/IServicioDeSorteo/ListarResponse")]
        GestorParaVentaDeLoteria.Modelo.Sorteos[] Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDeSorteo/Listar", ReplyAction="http://tempuri.org/IServicioDeSorteo/ListarResponse")]
        System.Threading.Tasks.Task<GestorParaVentaDeLoteria.Modelo.Sorteos[]> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDeSorteo/Agregar", ReplyAction="http://tempuri.org/IServicioDeSorteo/AgregarResponse")]
        void Agregar(GestorParaVentaDeLoteria.Modelo.Sorteos item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDeSorteo/Agregar", ReplyAction="http://tempuri.org/IServicioDeSorteo/AgregarResponse")]
        System.Threading.Tasks.Task AgregarAsync(GestorParaVentaDeLoteria.Modelo.Sorteos item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioDeSorteoChannel : GestorParaVentaDeLoteria.UI.ServicioDeSorteo.IServicioDeSorteo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioDeSorteoClient : System.ServiceModel.ClientBase<GestorParaVentaDeLoteria.UI.ServicioDeSorteo.IServicioDeSorteo>, GestorParaVentaDeLoteria.UI.ServicioDeSorteo.IServicioDeSorteo {
        
        public ServicioDeSorteoClient() {
        }
        
        public ServicioDeSorteoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioDeSorteoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDeSorteoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDeSorteoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GestorParaVentaDeLoteria.Modelo.Sorteos[] Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<GestorParaVentaDeLoteria.Modelo.Sorteos[]> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public void Agregar(GestorParaVentaDeLoteria.Modelo.Sorteos item) {
            base.Channel.Agregar(item);
        }
        
        public System.Threading.Tasks.Task AgregarAsync(GestorParaVentaDeLoteria.Modelo.Sorteos item) {
            return base.Channel.AgregarAsync(item);
        }
    }
}
